names:
- balcony-fence
- car
- facade
- fence
- non-building-infrastructure
- shop
- street
- traffic-infrastructure
- vegetation
- window
nc: 10
roboflow:
  license: CC BY 4.0
  project: building-facade-segmentation-instance
  url: https://universe.roboflow.com/building-facade/building-facade-segmentation-instance/dataset/1
  version: 1
  workspace: building-facade
test: /home/ubuntu/hslu-computer-vision/hslu-cv-facades/YOLOv8/building-facade-segmentation-instance-1/test/images
train: /home/ubuntu/hslu-computer-vision/hslu-cv-facades/YOLOv8/building-facade-segmentation-instance-1/train/images
val: /home/ubuntu/hslu-computer-vision/hslu-cv-facades/YOLOv8/building-facade-segmentation-instance-1/valid/images

# Data Augmentation ------------------------------------------------------------------------------------------------------
scale: 0.2  # image scale (+/- gain)
flipud: 0.7  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 0.3  # image mosaic (probability)
mixup: 0.5  # image mixup (probability)
hflip: 0.5 # apply random horizontal flipping
